# Generated by Django 5.2.6 on 2025-10-01 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                # ('author', models.CharField(max_length=100, null=True)),
                # ('is_bestselling', models.BooleanField(default=False)),
                # ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
    ]
