# Generated by Django 5.2.6 on 2025-10-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0007_address_author_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='post_code',
            field=models.CharField(default='00000', max_length=10),
        ),
    ]
