# Generated by Django 5.2.6 on 2025-10-04 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0008_address_post_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='post_code',
            new_name='postal_code',
        ),
    ]
